[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python -m ensurepip",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "gunicorn Backend.wsgi:application --bind 0.0.0.0:$PORT"
